### ISSUE TITLE
my payer looks strange

### ISSUE THREAD

**Issue by HybridDog** [Rui914/playeranim#1]
![screenshot_20150627_092539](https://cloud.githubusercontent.com/assets/3192173/8390968/948b8aee-1cae-11e5-80b4-261c5cf1565d.png)

**Comment by Rui914** [comment]
0955d80
Perhaps it was fixed.

**Comment by HybridDog** [comment]
What is a mc18 model?

**Comment by Rui914** [comment]
It is minecraft 1.8 compatible model (from Jordach's BFD).

**Comment by Rui914** [comment]
MC18 model was removed.
