### ISSUE TITLE
can't see my own player model

### ISSUE THREAD

**Issue by amadin** [Rui914/playeranim#2]
When viewed from a third party i can't see my own player model.

**Comment by Rui914** [comment]
Did you install other mods?

**Comment by amadin** [comment]
Last time i updated wrokbench mod and added teleport to spawn button to gui

**Comment by Rui914** [comment]
Can you tell me the link?

**Comment by amadin** [comment]
On local server playeranim work fine now, but yestuday on public server i can't see my player model in crtystal armor. There is no lik, i posted code here.

Workbench: 

-- Boilerplate to support localized strings if intllib mod is installed.
local S
if minetest.get_modpath("intllib") then
	S = intllib.Getter()
else
	-- If you don't use insertions (@1, @2, etc) you can use this:
	S = function(s) return s end

	-- If you use insertions, but not insertion escapes this will work:
	S = function(s,a,...)a={a,...}return s:gsub("@(%d+)",function(n)return a[tonumber(n)]end)end

	-- Use this if you require full functionality
	S = function(s,a,...)if a==nil then return s end a={a,...}return s:gsub("(@?)@(%(?)(%d+)(%)?)",function(e,o,n,c)if e==""then return a[tonumber(n)]..(o==""and c or"")else return"@"..o..n..c end end) end
end

local function item_drop(itemstack, dropper, pos)
--print("3")
	if dropper:is_player() then
		--print("4")
		local v = dropper:get_look_dir()
		local p = {x=pos.x, y=pos.y+1.2, z=pos.z}
		p.x = p.x+(math.random(1,3)*0.2)
		p.z = p.z+(math.random(1,3)*0.2)
		local obj = minetest.env:add_item(p, itemstack)
		if obj then
			v.x = v.x*4
			v.y = v.y*4 + 2
			v.z = v.z*4
			obj:setvelocity(v)
		--print("5")
		end
	else
		minetest.add_item(pos, itemstack)
		--print("6")
	end
	return itemstack
	
end

local function drop_fields(player, name)
	local inv = player:get_inventory()
	--print("1")
	for i,stack in ipairs(inv:get_list(name)) do
		item_drop(stack, player, player:getpos())
		stack:clear()
		inv:set_stack(name, i, stack)
		--print("2")
	end
end

minetest.register_on_joinplayer(function(player) -- вход игрока
	-- уменьшение инвентраря крафта игрока до 2х2
	local inv = player:get_inventory()
	inv:set_size("craft", 2*2)
	inv:set_width("craft", 2)
	-- уменьшение поля крафта в инвентаре игрока до 2х2
	local inv_f = player:get_inventory_formspec()
	local new_inv_f, i = string.gsub(inv_f, "list%[current_player;craft;(%d.-),(%d.-);[%d.]-,[%d.]-;%]", function(x, y) return "list[current_player;craft;" .. x+0.5 .."," .. y+0.5 .. ";2,2;]" end)
	player:set_inventory_formspec(new_inv_f)
end)

local wb_form = "size[8,8.5]" -- форма верстака
	..default.gui_bg
	..default.gui_bg_img
	..default.gui_slots
	.."list[current_player;main;0,4.25;8,1;]"
	.."list[current_player;main;0,5.5;8,3;8]"
	.."list[current_player;craft;1.75,0.5;3,3;]"
	.."list[current_player;craftpreview;5.75,1.5;1,1;]"
	.."image[4.75,1.5;1,1;gui_furnace_arrow_bg.png^[transformR270]"
	.."listring[current_player;main]"
	.."listring[current_player;craft]"
	..default.get_hotbar_bg(0,4.25)

minetest.register_on_player_receive_fields(function(player, formname, fields)
	if string.find(formname, "workbench") == 1 and fields.quit then -- выход с формы верстака
		local pos = minetest.string_to_pos(string.gsub(formname, "workbench", ""))
		local pl_inv = player:get_inventory()
		local wb_inv = minetest.get_meta(pos):get_inventory()
		-- переносим вещи из крафт-инвентаря игрока на инвентарь craft3 верстака
		-- wb_inv:set_list("craft3", pl_inv:get_list("craft"))
		-- уменьшаем крафт-инвентарь игрока (при этом он очищается?)
		drop_fields(player,"craft")
		pl_inv:set_size("craft", 2*2)
		pl_inv:set_width("craft", 2)
		
		-- переносим вещи из инвентаря craft2 верстака в крафт-инвентарь игрока
		pl_inv:set_list("craft", wb_inv:get_list("craft2"))--]]
	end

end)

minetest.register_node("workbench:3x3", { -- регистрация блока-верстака
	description = S("WorkBench"),
	tiles = {"workbench_3x3_top.png", "workbench_3x3_bottom.png", "workbench_3x3_side.png",
		"workbench_3x3_side.png", "workbench_3x3_side.png", "workbench_3x3_front.png"},
	paramtype2 = "facedir",
	groups = {choppy=2,oddly_breakable_by_hand=2},
	legacy_facedir_simple = true,
	sounds = default.node_sound_wood_defaults(),
	on_construct = function(pos)
		local meta = minetest.get_meta(pos)
		meta:set_string("infotext", "Workbench")
		local inv = meta:get_inventory()
		inv:set_size("craft2", 2*2)
		inv:set_width("craft2", 2)
		inv:set_size("craft3", 3*3)
		inv:set_width("craft3", 3)
	end,
	on_rightclick = function(pos, node, clicker, itemstack)
		--print(1)
		local pl_inv = clicker:get_inventory()
		--print(2)
		local wb_inv = minetest.get_meta(pos):get_inventory()
		--print(3)
		-- переносим вещи из крафт-инвентаря игрока на инвентарь craft2 верстака
		--wb_inv:set_list("craft2", pl_inv:get_list("craft"))
		--print(4)
		-- расширяем крафт-нивентарь игрока (при этом он очищается?)
		pl_inv:set_size("craft", 3*3)
		--print(5)
		pl_inv:set_width("craft", 3)
		--print(6)
		-- переносим вещи из инвентаря craft3 верстака в крафт-инвентарь игрока
		--pl_inv:set_list("craft", wb_inv:get_list("craft3"))
		--print(7)
		-- показываем форму с обновлённым крафт-полем
		minetest.show_formspec(clicker:get_player_name(), "workbench"..minetest.pos_to_string(pos), wb_form)
		--print(8)
	end,
})

minetest.register_craft({ -- крафт верстака
	output = 'workbench:3x3',
	recipe = {
		{'group:wood', 'group:wood', ''},
		{'group:wood', 'group:wood', ''},
		{'', '', ''},
	}
})

Button gui:

local homes_file = minetest.get_worldpath() .. "/beds_spawns"
local homepos = {}

function loadhomes()
    local input = io.open(homes_file, "r")
    if input then
      repeat
            local x = input:read("*n")
            if x == nil then
               break
            end
            local y = input:read("*n")
            local z = input:read("*n")
            local name = input:read("*l")
            homepos[name:sub(2)] = {x = x, y = y, z = z}
        until input:read(0) == nil
        io.close(input)
    else
        homepos = {}
    end
end

minetest.register_privilege("home", "Can use /sethome and /home")

minetest.register_chatcommand("home", {
    description = "Teleport you to your home point",
    privs = {home=true},
    func = function(name)
        local player = minetest.get_player_by_name(name)
        if player == nil then
            -- just a check to prevent the server crashing
            return false
        end
      loadhomes()
        if homepos[name] then
            player:setpos(homepos[name])
            --minetest.chat_send_player(name, "Teleported to home!")
        else
            minetest.chat_send_player(name, "You haven't slept in a bed yet.")
        end
    end,
})

minetest.register_chatcommand("sethome", {
    description = "Information about set your home point",
    func = function(name)
      minetest.chat_send_player(name, "You must sleep in a bed for this.")
    end,
})

**Comment by amadin** [comment]
Sorry "Button gui:" is wrong, this is other mod. This is right "Button_gui":

--[[

Home GUI for Minetest

Copyright (c) 2012 cornernote, Brett O'Donnell <cornernote@gmail.com>
Source Code: https://github.com/cornernote/minetest-home_gui
License: BSD-3-Clause https://raw.github.com/cornernote/minetest-home_gui/master/LICENSE

]]--

-- local api
local home_gui = {}
local timeout = 0
SPAWN_AFTER = 60

-- static spawn position
local statspawn = (minetest.setting_get_pos("static_spawnpoint") or {x = 0, y = 2, z = 0})

-- filename
home_gui.filename = minetest.get_worldpath()..'/home_gui'

-- load_home
--[[
local homepos = {}
local load_home = function()
local input = io.open(home_gui.filename..".home", "r")
   if input then
      while true do
         local x = input:read("*n")
         if x == nil then
            break
         end
         local y = input:read("*n")
         local z = input:read("*n")
         local name = input:read("*l")
         homepos[name:sub(2)] = {x = x, y = y, z = z}
      end
      io.close(input)
   else
      homepos = {}
   end
end

load_home() -- run it now

-- set_home
home_gui.set_home = function(player, pos)
   homepos[player:get_player_name()] = pos
   -- save the home data from the table to the file
   local output = io.open(home_gui.filename..".home", "w")
   for k, v in pairs(homepos) do
      if v ~= nil then
         v = vector.round(v)
         output:write(math.floor(v.x).." "..math.floor(v.y).." "..math.floor(v.z).." "..k.."\n")
      end
   end
   io.close(output)
end

-- go_home
home_gui.go_home = function(player)
   local pos = homepos[player:get_player_name()]
   if pos ~= nil then
      player:setpos(pos)
   else
      player:setpos(statspawn)
   end
end --]]
local spawn_after_func = function(player)
	timeout = 0
	return
end
-- go_spawn
home_gui.go_spawn = function(player)
	if timeout == 0 then
   player:setpos(statspawn)
	player:set_physics_override(1, 1, 1)
	player:set_eye_offset({x=0,y=0,z=0}, {x=0,y=0,z=0})
	player:set_look_yaw(math.random(1, 180)/100)
	default.player_set_animation(player, "stand" , 30)
	
	timeout = 1
	minetest.after(SPAWN_AFTER, spawn_after_func, player)

	else
local playerName = player:get_player_name()
minetest.chat_send_player(playerName, "You can do it once in " .. SPAWN_AFTER .. " seconds only")
end

end



-- get_formspec
home_gui.get_formspec = function(player)

   local formspec = "size[6,2]"
      ..default.gui_bg..default.gui_bg_img..default.gui_slots
      .."button[0,0;2,0.5;main;Back]"
      --.."button_exit[0,1.5;2,0.5;home_gui_set;Set Home]"
      --.."button_exit[2,1.5;2,0.5;home_gui_go;Go Home]"
      .."button_exit[2,1.5;2,0.5;home_gui_spawn;Spawn]"

   --[[local home = homepos[player:get_player_name()]

   if home ~= nil then
      formspec = formspec
         .."label[2.5,-0.2;Home set to:]"
         .."label[2.5,0.4;".. minetest.pos_to_string(vector.round(home)) .. "]"
   end
-]]
   return formspec
end

-- register_on_joinplayer
minetest.register_on_joinplayer(function(player)
   -- add inventory_plus page
   inventory_plus.register_button(player,"home_gui","Teleport")
end)

-- register_on_player_receive_fields
minetest.register_on_player_receive_fields(function(player, formname, fields)
   if fields.home_gui_set then
      home_gui.set_home(player, player:getpos())
   end
   if fields.home_gui_go then
      home_gui.go_home(player)
   end
   if fields.home_gui_spawn then
      home_gui.go_spawn(player)
   end
   if fields.home_gui or fields.home_gui_set or fields.home_gui_go then
      inventory_plus.set_inventory_formspec(player, home_gui.get_formspec(player))
   end
end)

**Comment by Rui914** [comment]
Umm...
Can you reinstall playeranim?

**Comment by amadin** [comment]
I was rollback it to version which after some time turning off player animation, because today server was crash more often than usual (without errors in log) and i don't know why it happens.

**Comment by Rui914** [comment]
Please update playeranim of server.
Maybe it is old version.

**Comment by amadin** [comment]
I will update tomorrow, maybe trouble in other mod, so tomorrow i will know exactly

**Comment by Rui914** [comment]
Hey.
Did this fix?

**Comment by amadin** [comment]
Now all right

**Comment by Rui914** [comment]
I see.
I'll close this issue.
