### ISSUE TITLE
Player looks crazy when local Normalmodel = true

### ISSUE THREAD

**Issue by sloantothebone** [Rui914/playeranim#3]
![screenshot_1074763186](https://cloud.githubusercontent.com/assets/9519585/8412320/b4d18280-1e4e-11e5-8fe0-4a8b7c899c75.png)
When I set it to false it works fine

**Comment by Rui914** [comment]
Are you enable the mod other than playeranim?

**Comment by sloantothebone** [comment]
Nope no other mods, this screenshot was taken in pure minetest

**Comment by Rui914** [comment]
Perhaps, should you update minetest_game.

**Comment by Rui914** [comment]
Perhaps, It fixed.
6df04a5
